### ISSUE TITLE
使用js脚本报错Invalid cross-device link

### ISSUE THREAD

**Issue by 1294266616** [GuGuNiu/Miao-Plugin-MBT#7]
bot：喵崽bot
环境：docker debin
下载完成后硬链过去报错了，两个文件夹都有挂载在宿主机不过理论上应该不会影响吧
部分报错日志：
应用错误：
Error: Command failed: cp -a -f -l ./resources/Miao-Plugin-MBT/* ./plugins/miao-plugin/resources/profile/
cp: cannot create hard link './plugins/miao-plugin/resources/profile/README.md' to './resources/Miao-Plugin-MBT/README.md': Invalid cross-device link
cp: cannot create hard link './plugins/miao-plugin/resources/profile/normal-character/'$'\344\270\271\346\201\222\342\200\242\351\245\256\346\234\210''/'$'\344\270\271\346\201\222''Gu2XR.webp' to './resources/Miao-Plugin-MBT/normal-character/'$'\344\270\271\346\201\222\342\200\242\351\245\256\346\234\210''/'$'\344\270\271\346\201\222''Gu2XR.webp': Invalid cross-device link
cp: cannot create hard link './plugins/miao-plugin/resources/profile/normal-character/'$'\345\205\213\346\264\233\347\220\263\345\276\267''/'$'\345\205\213\346\264\233\347\220\263\345\276\267''Gu3.webp' to './resources/Miao-Plugin-MBT/normal-character/'$'\345\205\213\346\264\233\347\220\263\345\276\267''/'$'\345\205\213\346\264\233\347\220\263\345\276\267''Gu3.webp': Invalid cross-device link

**Comment by GuGuNiu** [comment]
跨系统可能要用软链接吧 你可以自己改一下js

**Comment by 1294266616** [comment]
> 跨系统可能要用软链接吧 你可以自己改一下js

自己去找资料，都挂载了还真会影响只能用其他方法了
