### ISSUE TITLE
为什么角色图片不显示区域在面板图还是会显示

### ISSUE THREAD

**Issue by A-Kevin1217** [GuGuNiu/Miao-Plugin-MBT#8]
![IMG_6765](https://github.com/GuGuNiu/Miao-Plugin-MBT/assets/21151999/cb8a400d-800b-455b-a165-818729634961)

**Comment by A-Kevin1217** [comment]
亦或者说 在TRSS云崽下载的图片没有生效

**Comment by A-Kevin1217** [comment]
> ![IMG_6765](https://private-user-images.githubusercontent.com/21151999/302056028-cb8a400d-800b-455b-a165-818729634961.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5ODc0MzEsIm5iZiI6MTcwNjk4NzEzMSwicGF0aCI6Ii8yMTE1MTk5OS8zMDIwNTYwMjgtY2I4YTQwMGQtODAwYi00NTViLWExNjUtODE4NzI5NjM0OTYxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxOTA1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzE2ZjUyMDJjNjZlN2RjNmU3MDFkMjg4NGIwYjQ1YzA2OTE2OGY3ZjNhMTQ0ODUyOTljMjg4ODhkZGMwMDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V8VbtQkvhS5AHNFxlQ4t_7Vdgk11H_rVF1IrU8mGbcU)

这个是我手动移动图片文件到喵喵目录去的

**Comment by GuGuNiu** [comment]
我这里是面板图 不是角色写真图

**Comment by A-Kevin1217** [comment]
> 我这里是面板图 不是角色写真图

好的谢谢
