### ISSUE TITLE
Js插件命令下载失败

### ISSUE THREAD

**Issue by lulu-la** [GuGuNiu/Miao-Plugin-MBT#9]
![Uploading A8C2BBB4EA90605C03FB00EAA0512E3E.png…]()

**Comment by lulu-la** [comment]
<img width="544" alt="A8C2BBB4EA90605C03FB00EAA0512E3E" src="https://github.com/GuGuNiu/Miao-Plugin-MBT/assets/62944554/b27efa52-a1c5-43b5-9933-eb6f8e4d5adf">

**Comment by GuGuNiu** [comment]
开梯子
